### ISSUE TITLE
Cannot reset commerce data

### ISSUE THREAD

**Issue by rjanits** [lenvanessen/commerce-invoices#1]
When I tried to reset the commerce data I got the following error message:
<img width="1257" alt="Bildschirmfoto 2022-02-22 um 17 04 30" src="https://user-images.githubusercontent.com/5663806/155172362-a3e79cbf-0d32-4b24-9dca-4117e6865e44.png">

### Steps to reproduce
- Install Craft Commerce and Commerce Invoices
- Create Orders and Invoices as you described
- Reset the commerce data using `php craft commerce/reset-data`

### Additional info
- Craft version: 3.7.27.2
- Commerce version: 3.4.10.1
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34
- Commerce-Invoices version: 0.1.1

_Edit: Added plugin version to additional info_

**Comment by lenvanessen** [comment]
@rjanits thanks for reporting! I'll try and take a wack at it if I find some time later this week!

**Comment by rjanits** [comment]
@lenvanessen btw.. what is the latest version of this plugin? Composer Package says 0.1.1 but the github shows me partially different code.

**Comment by lenvanessen** [comment]
@rjanits thanks for reporting, sorry something went wrong with the tagging. You should be able to update to 0.1.9 right now, which has a fix for your original issue.

I've also added the missing tags.
